"""empty message

Revision ID: 23afb19cdfb7
Revises: 8774b4541219
Create Date: 2018-06-11 17:24:49.935514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23afb19cdfb7'
down_revision = '8774b4541219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
